redisdb:
  image: busybox
  volumes:
    - /var/lib/redis

postgresqldb:
  image: busybox
  volumes:
    - /var/lib/postgresql/data

redis:
  image: redis:3
  volumes_from:
    - redisdb
  ports:
    - "6379:6379"

postgresql:
  image: postgres:9
  volumes_from:
    - postgresqldb
  environment:
    POSTGRES_USER: laura
    POSTGRES_PASSWORD: laura
  ports:
    - "5432:5432"

tomcat:
  image: library/tomcat:8-jre8
  links:
    - redis
    - postgresql
  ports:
    - "8080:8080"
